name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive files for deployment
        run: |
          mkdir deployment
          cp -r dist deployment/
          cp package.json deployment/
          cp package-lock.json deployment/
          tar -czf deployment.tar.gz deployment

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          target: ${{ secrets.FTP_PATH }}
          source: deployment.tar.gz
          rm: true
          debug: true

      - name: Cleanup archive
        run: rm -rf deployment deployment.tar.gz
