name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List files for debugging
        run: ls -la

      - name: Archive files for upload
        run: |
          tar -czf build.tar.gz dist package.json

      - name: Clean remote directory
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            rm -rf ${{ secrets.FTP_PATH }}/*

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          target: ${{ secrets.FTP_PATH }}
          source: build.tar.gz

      - name: Extract files on server
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd ${{ secrets.FTP_PATH }}
            tar -xzf build.tar.gz
            rm build.tar.gz

      - name: Install dependencies on server
        run: |
          ssh ${{ secrets.FTP_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.FTP_PATH }}
          npm install --only=production
          EOF
