name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive files for deployment
        run: |
          mkdir deployment
          cp -r dist deployment/
          cp package.json deployment/
          cp package-lock.json deployment/
          tar -czf deployment.tar.gz deployment

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          target: ${{ secrets.FTP_PATH }}
          source: deployment.tar.gz
          rm: true
          debug: true

      - name: Extract files on the server and install dependencies
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd ${{ secrets.FTP_PATH }}
            echo "Розпаковую архів..."
            tar -xzf deployment.tar.gz || { echo "Розпакування не вдалося"; exit 1; }
            echo "Файли після розпакування:"
            ls -la deployment
            mv deployment/* . || { echo "Переміщення файлів не вдалося"; exit 1; }
            rm -rf deployment deployment.tar.gz

            echo "Перевірка доступності Node.js..."
            if ! command -v node &> /dev/null; then
              echo "Node.js не встановлено. Встановлюю Node.js..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            else
              echo "Node.js вже встановлено:"
              node --version
            fi

            echo "Перевірка доступності npm..."
            npm --version || { echo "npm не встановлено"; exit 1; }

            echo "Встановлюю залежності..."
            npm install --production || { echo "Встановлення залежностей не вдалося"; exit 1; }
  
