name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive files for deployment
        run: |
          mkdir deployment
          cp -r dist deployment/
          cp package.json deployment/
          cp package-lock.json deployment/
          tar -czf deployment.tar.gz deployment

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          target: ${{ secrets.FTP_PATH }}
          source: deployment.tar.gz
          rm: true
          debug: true

      - name: Extract files on the server and install dependencies
        run: |
          sshpass -p "${{ secrets.FTP_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.FTP_PATH }}
          echo "Розпаковую архів..."
          tar -xzf deployment.tar.gz || { echo "Розпакування не вдалося"; exit 1; }
          echo "Файли після розпакування:"
          ls -la deployment
          mv deployment/* . || { echo "Переміщення файлів не вдалося"; exit 1; }
          rm -rf deployment deployment.tar.gz

          echo "Перевірка доступності Node.js..."
          if ! command -v node &> /dev/null; then
            echo "Node.js не встановлено. Спроба встановлення..."
            if [ -f /etc/debian_version ]; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | bash - || { echo "Помилка встановлення Node.js"; exit 1; }
              apt-get install -y nodejs || { echo "Помилка встановлення nodejs"; exit 1; }
            elif [ -f /etc/redhat-release ]; then
              curl -fsSL https://rpm.nodesource.com/setup_18.x | bash - || { echo "Помилка встановлення Node.js"; exit 1; }
              yum install -y nodejs || { echo "Помилка встановлення nodejs"; exit 1; }
            else
              echo "Невідома операційна система. Встановіть Node.js вручну."; exit 1;
            fi
          else
            echo "Node.js вже встановлено:"
            node --version
          fi

          echo "Перевірка доступності npm..."
          if ! command -v npm &> /dev/null; then
            echo "npm не встановлено. Спроба встановити..."
            if [ -f /etc/debian_version ]; then
              apt-get install -y npm || { echo "Помилка встановлення npm"; exit 1; }
            elif [ -f /etc/redhat-release ]; then
              yum install -y npm || { echo "Помилка встановлення npm"; exit 1; }
            else
              echo "Невідома операційна система. Встановіть npm вручну."; exit 1;
            fi
          else
            echo "npm вже встановлено:"
            npm --version
          fi

          echo "Встановлюю залежності..."
          npm install --production || { echo "Встановлення залежностей не вдалося"; exit 1; }