name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      # Клонування репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # Встановлення залежностей локально
      - name: Install dependencies
        run: npm install

      # Збірка проекту
      - name: Build project
        run: npm run build

      # Архівування файлів для завантаження
      - name: Archive files for upload
        run: |
          tar -czf build.tar.gz dist package.json package-lock.json

      # Очищення віддаленої папки
      - name: Clean remote directory
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            rm -rf ${{ secrets.FTP_PATH }}/*

      # Завантаження файлів на сервер
      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          target: ${{ secrets.FTP_PATH }}
          source: build.tar.gz

      # Налаштування Node.js, встановлення залежностей і запуск
      - name: Extract files and setup Node.js
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            # Перехід до папки з проєктом
            cd ${{ secrets.FTP_PATH }}
      
            # Розпакування архіву
            echo "Extracting deployment package..."
            tar -xzf build.tar.gz || { echo "Failed to extract archive"; exit 1; }
            rm build.tar.gz
      
            # Оновлення середовища для Node.js
            echo "Updating Node.js environment..."
            source ~/.bashrc || echo "No .bashrc to source"
      
            # Перевірка наявності Node.js
            if ! command -v node &> /dev/null; then
              echo "Node.js is not installed! Please check your hosting environment."
              exit 1
            fi
            echo "Node.js version: $(node -v)"
      
            # Встановлення залежностей
            echo "Installing dependencies..."
            if ! npm install --production; then
              echo "Dependency installation failed!"
              exit 1
            fi
      
            # Експортування змінних середовища
            echo "Setting environment variables..."
            export NODE_ENV=production
            export DB_NAME=${{ secrets.DB_NAME }}
      
            # (За потреби) Перезапуск через PM2
            if command -v pm2 &> /dev/null; then
              echo "Restarting application via PM2..."
              pm2 restart all || echo "PM2 restart failed!"
            else
              echo "PM2 is not installed or not configured. Skipping PM2 restart."
            fi
