name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      # Крок 1: Клонування коду з репозиторію
      - name: Checkout code
        uses: actions/checkout@v4

      # Крок 2: Встановлення залежностей локально
      - name: Install dependencies
        run: npm install

      # Крок 3: Білд проекту
      - name: Build project
        run: npm run build

      # Крок 4: Завантаження файлів на сервер
      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          target: ${{ secrets.FTP_PATH }}
          source: |
            ./dist/**
            ./package.json
            ./package-lock.json
            ./.env # Якщо використовується .env-файл
          rm: true # Видаляти старі файли перед завантаженням

      # Крок 5: Встановлення залежностей на сервері
      - name: Install dependencies on server
        run: |
          ssh ${{ secrets.FTP_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          cd ${{ secrets.FTP_PATH }}
          npm install --only=production
          EOF
